//! Error types for tensor4all-hdf5-ffi.

use std::convert::Infallible;
use std::error::Error as StdError;
use std::fmt;
use std::io;

use ndarray::ShapeError;

use crate::sys::{herr_t, hid_t, hsize_t};

/// The error type for HDF5-related functions.
#[derive(Clone, Debug)]
pub enum Error {
    /// The HDF5 library has not been initialized.
    NotInitialized,
    /// The HDF5 library was already initialized with a different path.
    AlreadyInitialized(String),
    /// Failed to load the HDF5 library.
    LibraryLoad { path: String, source: String },
    /// An error occurred in the HDF5 C library.
    Hdf5(String),
    /// A user error occurred in the high-level Rust API.
    Internal(String),
}

/// A type for results generated by HDF5-related functions.
pub type Result<T, E = Error> = std::result::Result<T, E>;

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::NotInitialized => write!(f, "HDF5 library not initialized"),
            Self::AlreadyInitialized(path) => {
                write!(f, "HDF5 library already initialized with path: {}", path)
            }
            Self::LibraryLoad { path, source } => {
                write!(f, "Failed to load HDF5 library from {}: {}", path, source)
            }
            Self::Hdf5(msg) => write!(f, "HDF5 error: {}", msg),
            Self::Internal(msg) => write!(f, "{}", msg),
        }
    }
}

impl StdError for Error {}

impl From<&str> for Error {
    fn from(desc: &str) -> Self {
        Self::Internal(desc.into())
    }
}

impl From<String> for Error {
    fn from(desc: String) -> Self {
        Self::Internal(desc)
    }
}

impl From<Infallible> for Error {
    fn from(_: Infallible) -> Self {
        unreachable!("Infallible error can never be constructed")
    }
}

impl From<ShapeError> for Error {
    fn from(err: ShapeError) -> Self {
        format!("shape error: {err}").into()
    }
}

impl From<Error> for io::Error {
    fn from(err: Error) -> Self {
        Self::new(io::ErrorKind::Other, err)
    }
}

/// Check HDF5 return value and convert to Result.
pub fn h5check<T: H5ErrorCode>(value: T) -> Result<T> {
    H5ErrorCode::h5check(value)
}

/// Check if a value indicates an error.
#[allow(unused)]
pub fn is_err_code<T: H5ErrorCode>(value: T) -> bool {
    H5ErrorCode::is_err_code(value)
}

/// Trait for HDF5 error codes.
pub trait H5ErrorCode: Copy {
    fn is_err_code(value: Self) -> bool;

    fn h5check(value: Self) -> Result<Self> {
        if Self::is_err_code(value) {
            Err(Error::Hdf5("HDF5 operation failed".into()))
        } else {
            Ok(value)
        }
    }
}

impl H5ErrorCode for hsize_t {
    fn is_err_code(value: Self) -> bool {
        value == 0
    }
}

impl H5ErrorCode for herr_t {
    fn is_err_code(value: Self) -> bool {
        value < 0
    }
}

impl H5ErrorCode for hid_t {
    fn is_err_code(value: Self) -> bool {
        value < 0
    }
}

impl H5ErrorCode for libc::ssize_t {
    fn is_err_code(value: Self) -> bool {
        value < 0
    }
}
