#ifndef TENSOR4ALL_CAPI_H
#define TENSOR4ALL_CAPI_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Boundary-condition choices for quantics transform materialization.
 */
typedef enum t4a_boundary_condition {
  /**
   * Periodic boundary conditions.
   */
  T4A_BOUNDARY_CONDITION_PERIODIC = 0,
  /**
   * Open boundary conditions.
   */
  T4A_BOUNDARY_CONDITION_OPEN = 1,
} t4a_boundary_condition;

/**
 * Canonical binary QTT layout kinds supported by the reduced C API.
 */
typedef enum t4a_qtt_layout_kind {
  /**
   * Variable-major grouped layout.
   */
  T4A_QTT_LAYOUT_KIND_GROUPED = 0,
  /**
   * Level-major interleaved layout.
   */
  T4A_QTT_LAYOUT_KIND_INTERLEAVED = 1,
  /**
   * Fused-per-level layout.
   */
  T4A_QTT_LAYOUT_KIND_FUSED = 2,
} t4a_qtt_layout_kind;

/**
 * Scalar kind used by the reduced tensor surface.
 */
typedef enum t4a_scalar_kind {
  /**
   * Real-valued `f64` data.
   */
  T4A_SCALAR_KIND_F64 = 0,
  /**
   * Complex-valued `Complex64` data represented as interleaved doubles.
   */
  T4A_SCALAR_KIND_C64 = 1,
} t4a_scalar_kind;

/**
 * TreeTN contraction method exposed through the C API.
 */
typedef enum t4a_contract_method {
  /**
   * Zip-up contraction with on-the-fly truncation.
   */
  T4A_CONTRACT_METHOD_ZIPUP = 0,
  /**
   * Variational fit-based contraction.
   */
  T4A_CONTRACT_METHOD_FIT = 1,
  /**
   * Naive dense contraction.
   */
  T4A_CONTRACT_METHOD_NAIVE = 2,
} t4a_contract_method;

/**
 * Canonical form used for orthogonalization/truncation.
 */
typedef enum t4a_canonical_form {
  /**
   * Unitary / QR-based canonicalization.
   */
  T4A_CANONICAL_FORM_UNITARY = 0,
  /**
   * LU-based canonicalization.
   */
  T4A_CANONICAL_FORM_LU = 1,
  /**
   * Cross-interpolation-based canonicalization.
   */
  T4A_CANONICAL_FORM_CI = 2,
} t4a_canonical_form;

/**
 * Status code type for C API
 */
typedef int StatusCode;

/**
 * Opaque index type for the C API.
 */
typedef struct t4a_index {
  const void *_private;
} t4a_index;

/**
 * Opaque canonical QTT layout descriptor.
 */
typedef struct t4a_qtt_layout {
  const void *_private;
} t4a_qtt_layout;

/**
 * Opaque tree tensor network type for the C API.
 */
typedef struct t4a_treetn {
  const void *_private;
} t4a_treetn;

/**
 * Opaque tensor type for the C API.
 */
typedef struct t4a_tensor {
  const void *_private;
} t4a_tensor;

/**
 * The provided output buffer is too small for the result.
 */
#define T4A_BUFFER_TOO_SMALL -5

/**
 * An internal error occurred (e.g., a panic was caught).
 */
#define T4A_INTERNAL_ERROR -6

/**
 * An invalid argument was provided.
 */
#define T4A_INVALID_ARGUMENT -2

/**
 * The requested API exists but is not implemented yet.
 */
#define T4A_NOT_IMPLEMENTED -7

/**
 * A null pointer was passed where a valid pointer was required.
 */
#define T4A_NULL_POINTER -1

/**
 * Operation completed successfully.
 */
#define T4A_SUCCESS 0

/**
 * Too many tags would be added to a TagSet (exceeds maximum).
 */
#define T4A_TAG_OVERFLOW -3

/**
 * A tag string exceeds the maximum allowed length.
 */
#define T4A_TAG_TOO_LONG -4

/**
 * Clone an index handle.
 */
StatusCode t4a_index_clone(const struct t4a_index *src, struct t4a_index **out);

/**
 * Get the dimension of an index.
 */
StatusCode t4a_index_dim(const struct t4a_index *ptr, size_t *out_dim);

/**
 * Query whether an index has the provided tag.
 */
StatusCode t4a_index_has_tag(const struct t4a_index *ptr, const char *tag, int32_t *out_has_tag);

/**
 * Get the 64-bit ID of an index.
 */
StatusCode t4a_index_id(const struct t4a_index *ptr, uint64_t *out_id);

/**
 * Check whether an index handle is assigned.
 */
int32_t t4a_index_is_assigned(const struct t4a_index *obj);

/**
 * Create a new index with explicit tags and prime level.
 */
StatusCode t4a_index_new(size_t dim, const char *tags_csv, int64_t plev, struct t4a_index **out);

/**
 * Create a new index with an explicit 64-bit ID.
 */
StatusCode t4a_index_new_with_id(size_t dim,
                                 uint64_t id,
                                 const char *tags_csv,
                                 int64_t plev,
                                 struct t4a_index **out);

/**
 * Get the prime level of an index.
 */
StatusCode t4a_index_plev(const struct t4a_index *ptr, int64_t *out_plev);

/**
 * Release an index handle.
 */
void t4a_index_release(struct t4a_index *obj);

/**
 * Copy tags as a comma-separated UTF-8 string.
 */
StatusCode t4a_index_tags(const struct t4a_index *ptr,
                          uint8_t *buf,
                          size_t buf_len,
                          size_t *out_len);

/**
 * Retrieve the last error message.
 *
 * # Arguments
 * * `buf` - Output buffer for the error message (UTF-8, null-terminated).
 *   Pass null to query required length only.
 * * `buf_len` - Size of the buffer in bytes.
 * * `out_len` - Output: required buffer length including null terminator.
 *
 * # Returns
 * * `T4A_SUCCESS` - Message written (or length query succeeded).
 * * `T4A_NULL_POINTER` - `out_len` is null.
 * * `T4A_BUFFER_TOO_SMALL` - Buffer too small; `out_len` has the required size.
 */
StatusCode t4a_last_error_message(uint8_t *buf, size_t buf_len, size_t *out_len);

/**
 * Materialize an affine transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_affine_materialize(const struct t4a_qtt_layout *layout,
                                             const int64_t *a_num,
                                             const int64_t *a_den,
                                             const int64_t *b_num,
                                             const int64_t *b_den,
                                             size_t m,
                                             size_t n,
                                             const enum t4a_boundary_condition *bc,
                                             struct t4a_treetn **out);

/**
 * Materialize a binary operator directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_binaryop_materialize(const struct t4a_qtt_layout *layout,
                                               size_t lhs_var,
                                               size_t rhs_var,
                                               int8_t a1,
                                               int8_t b1,
                                               int8_t a2,
                                               int8_t b2,
                                               enum t4a_boundary_condition bc1,
                                               enum t4a_boundary_condition bc2,
                                               struct t4a_treetn **out);

/**
 * Materialize a cumulative-sum transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_cumsum_materialize(const struct t4a_qtt_layout *layout,
                                             size_t target_var,
                                             struct t4a_treetn **out);

/**
 * Materialize a flip transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_flip_materialize(const struct t4a_qtt_layout *layout,
                                           size_t target_var,
                                           enum t4a_boundary_condition bc,
                                           struct t4a_treetn **out);

/**
 * Materialize a Fourier transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_fourier_materialize(const struct t4a_qtt_layout *layout,
                                              size_t target_var,
                                              int32_t forward,
                                              size_t maxbonddim,
                                              double tolerance,
                                              struct t4a_treetn **out);

/**
 * Materialize a phase-rotation transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_phase_rotation_materialize(const struct t4a_qtt_layout *layout,
                                                     size_t target_var,
                                                     double theta,
                                                     struct t4a_treetn **out);

/**
 * Materialize a shift transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_shift_materialize(const struct t4a_qtt_layout *layout,
                                            size_t target_var,
                                            int64_t offset,
                                            enum t4a_boundary_condition bc,
                                            struct t4a_treetn **out);

/**
 * Clone a QTT layout handle.
 */
StatusCode t4a_qtt_layout_clone(const struct t4a_qtt_layout *src, struct t4a_qtt_layout **out);

/**
 * Check whether a QTT layout handle is assigned.
 */
int32_t t4a_qtt_layout_is_assigned(const struct t4a_qtt_layout *obj);

/**
 * Create an immutable canonical QTT layout descriptor.
 */
StatusCode t4a_qtt_layout_new(enum t4a_qtt_layout_kind kind,
                              size_t nvariables,
                              const size_t *variable_resolutions,
                              struct t4a_qtt_layout **out);

/**
 * Release a QTT layout handle.
 */
void t4a_qtt_layout_release(struct t4a_qtt_layout *obj);

/**
 * Clone a tensor handle.
 */
StatusCode t4a_tensor_clone(const struct t4a_tensor *src, struct t4a_tensor **out);

/**
 * Contract two tensors by matching common indices.
 */
StatusCode t4a_tensor_contract(const struct t4a_tensor *a,
                               const struct t4a_tensor *b,
                               struct t4a_tensor **out);

/**
 * Copy dense `Complex64` data as interleaved doubles in column-major order.
 */
StatusCode t4a_tensor_copy_dense_c64(const struct t4a_tensor *ptr,
                                     double *buf_interleaved,
                                     size_t n_complex,
                                     size_t *out_len);

/**
 * Copy dense `f64` data in column-major order.
 */
StatusCode t4a_tensor_copy_dense_f64(const struct t4a_tensor *ptr,
                                     double *buf,
                                     size_t buf_len,
                                     size_t *out_len);

/**
 * Copy tensor dimensions in index order.
 */
StatusCode t4a_tensor_dims(const struct t4a_tensor *ptr,
                           size_t *buf,
                           size_t buf_len,
                           size_t *out_len);

/**
 * Copy cloned index handles describing the tensor axes.
 */
StatusCode t4a_tensor_indices(const struct t4a_tensor *ptr,
                              struct t4a_index **buf,
                              size_t buf_len,
                              size_t *out_len);

/**
 * Check whether a tensor handle is assigned.
 */
int32_t t4a_tensor_is_assigned(const struct t4a_tensor *obj);

/**
 * Create a dense complex tensor from interleaved column-major data.
 */
StatusCode t4a_tensor_new_dense_c64(size_t rank,
                                    const struct t4a_index *const *index_ptrs,
                                    const double *data_interleaved,
                                    size_t n_complex,
                                    struct t4a_tensor **out);

/**
 * Create a dense real tensor from column-major data.
 */
StatusCode t4a_tensor_new_dense_f64(size_t rank,
                                    const struct t4a_index *const *index_ptrs,
                                    const double *data,
                                    size_t data_len,
                                    struct t4a_tensor **out);

/**
 * Get the rank of a tensor.
 */
StatusCode t4a_tensor_rank(const struct t4a_tensor *ptr, size_t *out_rank);

/**
 * Release a tensor handle.
 */
void t4a_tensor_release(struct t4a_tensor *obj);

/**
 * Get the scalar kind of a tensor.
 */
StatusCode t4a_tensor_scalar_kind(const struct t4a_tensor *ptr, enum t4a_scalar_kind *out_kind);

/**
 * Apply a chain-compatible operator TreeTN to a chain state TreeTN.
 *
 * The operator must use dense node names `0..m-1`. `mapped_positions[i]`
 * specifies which state-chain node the operator node `i` acts on. Each mapped
 * operator node must have exactly two site indices, and the corresponding
 * `internal_input_indices[i]` and `internal_output_indices[i]` must point to
 * those indices. Unmapped state nodes are filled with identities by
 * `apply_linear_operator`.
 */
StatusCode t4a_treetn_apply_operator_chain(const struct t4a_treetn *operator_,
                                           const struct t4a_treetn *state,
                                           const size_t *mapped_positions,
                                           size_t n_mapped_positions,
                                           const struct t4a_index *const *internal_input_indices,
                                           const struct t4a_index *const *internal_output_indices,
                                           const struct t4a_index *const *true_output_indices,
                                           enum t4a_contract_method method,
                                           double rtol,
                                           double cutoff,
                                           size_t maxdim,
                                           struct t4a_treetn **out);

/**
 * Clone a TreeTN handle.
 */
StatusCode t4a_treetn_clone(const struct t4a_treetn *src, struct t4a_treetn **out);

/**
 * Contract two tree tensor networks with the requested method.
 */
StatusCode t4a_treetn_contract(const struct t4a_treetn *a,
                               const struct t4a_treetn *b,
                               enum t4a_contract_method method,
                               double rtol,
                               double cutoff,
                               size_t maxdim,
                               struct t4a_treetn **out);

/**
 * Evaluate a TreeTN at one or more points using explicit index handles.
 */
StatusCode t4a_treetn_evaluate(const struct t4a_treetn *treetn,
                               const struct t4a_index *const *indices,
                               size_t n_indices,
                               const size_t *values_col_major,
                               size_t n_points,
                               double *out_re,
                               double *out_im);

/**
 * Compute the inner product of two tree tensor networks.
 */
StatusCode t4a_treetn_inner(const struct t4a_treetn *a,
                            const struct t4a_treetn *b,
                            double *out_re,
                            double *out_im);

/**
 * Check whether a TreeTN handle is assigned.
 */
int32_t t4a_treetn_is_assigned(const struct t4a_treetn *obj);

/**
 * Get the bond index on the edge between two vertices.
 */
StatusCode t4a_treetn_linkind(const struct t4a_treetn *treetn,
                              size_t v1,
                              size_t v2,
                              struct t4a_index **out);

/**
 * Get the neighbors of a vertex.
 */
StatusCode t4a_treetn_neighbors(const struct t4a_treetn *treetn,
                                size_t vertex,
                                size_t *buf,
                                size_t buf_len,
                                size_t *out_len);

/**
 * Create a tree tensor network from an array of tensors.
 */
StatusCode t4a_treetn_new(const struct t4a_tensor *const *tensors,
                          size_t n_tensors,
                          struct t4a_treetn **out);

/**
 * Compute the norm of the tree tensor network.
 */
StatusCode t4a_treetn_norm(struct t4a_treetn *treetn, double *out_norm);

/**
 * Get the number of vertices in the tree tensor network.
 */
StatusCode t4a_treetn_num_vertices(const struct t4a_treetn *treetn, size_t *out_n);

/**
 * Orthogonalize the tree tensor network to a vertex using the requested form.
 */
StatusCode t4a_treetn_orthogonalize(struct t4a_treetn *treetn,
                                    size_t vertex,
                                    enum t4a_canonical_form form);

/**
 * Release a TreeTN handle.
 */
void t4a_treetn_release(struct t4a_treetn *obj);

/**
 * Replace the tensor at a specific vertex.
 */
StatusCode t4a_treetn_set_tensor(struct t4a_treetn *treetn,
                                 size_t vertex,
                                 const struct t4a_tensor *tensor);

/**
 * Get the site indices attached to a vertex.
 */
StatusCode t4a_treetn_siteinds(const struct t4a_treetn *treetn,
                               size_t vertex,
                               struct t4a_index **buf,
                               size_t buf_len,
                               size_t *out_len);

/**
 * Get the tensor at a specific vertex.
 */
StatusCode t4a_treetn_tensor(const struct t4a_treetn *treetn,
                             size_t vertex,
                             struct t4a_tensor **out);

/**
 * Contract all bonds and materialize the TreeTN as a dense tensor.
 */
StatusCode t4a_treetn_to_dense(const struct t4a_treetn *treetn, struct t4a_tensor **out);

/**
 * Truncate the tree tensor network bond dimensions.
 */
StatusCode t4a_treetn_truncate(struct t4a_treetn *treetn,
                               double rtol,
                               double cutoff,
                               size_t maxdim);

#endif  /* TENSOR4ALL_CAPI_H */
