#ifndef TENSOR4ALL_CAPI_H
#define TENSOR4ALL_CAPI_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Warning: this file is autogenerated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Boundary-condition choices for quantics transform materialization.
 */
typedef enum t4a_boundary_condition {
  /**
   * Periodic boundary conditions.
   */
  T4A_BOUNDARY_CONDITION_PERIODIC = 0,
  /**
   * Open boundary conditions.
   */
  T4A_BOUNDARY_CONDITION_OPEN = 1,
} t4a_boundary_condition;

/**
 * Canonical binary QTT layout kinds supported by the reduced C API.
 */
typedef enum t4a_qtt_layout_kind {
  /**
   * Level-major interleaved layout.
   */
  T4A_QTT_LAYOUT_KIND_INTERLEAVED = 0,
  /**
   * Fused-per-level layout.
   */
  T4A_QTT_LAYOUT_KIND_FUSED = 1,
} t4a_qtt_layout_kind;

/**
 * Scalar kind used by the reduced tensor surface.
 */
typedef enum t4a_scalar_kind {
  /**
   * Real-valued `f64` data.
   */
  T4A_SCALAR_KIND_F64 = 0,
  /**
   * Complex-valued `Complex64` data represented as interleaved doubles.
   */
  T4A_SCALAR_KIND_C64 = 1,
} t4a_scalar_kind;

/**
 * Storage layout kind used by tensor payload inspection APIs.
 */
typedef enum t4a_storage_kind {
  /**
   * Dense storage whose payload axes match the logical tensor axes.
   */
  T4A_STORAGE_KIND_DENSE = 0,
  /**
   * Diagonal storage whose logical axes all share one payload axis.
   */
  T4A_STORAGE_KIND_DIAGONAL = 1,
  /**
   * General structured storage with explicit payload-axis classes.
   */
  T4A_STORAGE_KIND_STRUCTURED = 2,
} t4a_storage_kind;

/**
 * Threshold scaling used by the C API SVD truncation policy.
 *
 * Related types:
 * - [`t4a_singular_value_measure`] selects whether the threshold is applied to
 *   singular values or squared singular values.
 * - [`t4a_truncation_rule`] selects whether the threshold is checked per value
 *   or against the discarded suffix sum.
 * - [`t4a_svd_truncation_policy`] combines all three knobs with the numeric
 *   threshold.
 *
 * # Examples
 *
 * ```
 * use tensor4all_capi::t4a_threshold_scale;
 * use tensor4all_core::ThresholdScale;
 *
 * assert_eq!(
 *     ThresholdScale::from(t4a_threshold_scale::Relative),
 *     ThresholdScale::Relative
 * );
 * assert_eq!(
 *     ThresholdScale::from(t4a_threshold_scale::Absolute),
 *     ThresholdScale::Absolute
 * );
 * ```
 */
typedef enum t4a_threshold_scale {
  /**
   * Compare the threshold to a singular-value-derived reference scale.
   */
  T4A_THRESHOLD_SCALE_RELATIVE = 0,
  /**
   * Compare the threshold directly to the measured singular-value quantity.
   */
  T4A_THRESHOLD_SCALE_ABSOLUTE = 1,
} t4a_threshold_scale;

/**
 * Singular-value quantity used by the C API SVD truncation policy.
 *
 * Related types:
 * - [`t4a_threshold_scale`] selects whether the threshold is relative or
 *   absolute.
 * - [`t4a_truncation_rule`] selects whether truncation is per value or based
 *   on the discarded tail sum.
 * - [`t4a_svd_truncation_policy`] stores the full C-facing SVD policy.
 *
 * # Examples
 *
 * ```
 * use tensor4all_capi::t4a_singular_value_measure;
 * use tensor4all_core::SingularValueMeasure;
 *
 * assert_eq!(
 *     SingularValueMeasure::from(t4a_singular_value_measure::Value),
 *     SingularValueMeasure::Value
 * );
 * assert_eq!(
 *     SingularValueMeasure::from(t4a_singular_value_measure::SquaredValue),
 *     SingularValueMeasure::SquaredValue
 * );
 * ```
 */
typedef enum t4a_singular_value_measure {
  /**
   * Measure singular values directly.
   */
  T4A_SINGULAR_VALUE_MEASURE_VALUE = 0,
  /**
   * Measure squared singular values.
   */
  T4A_SINGULAR_VALUE_MEASURE_SQUARED_VALUE = 1,
} t4a_singular_value_measure;

/**
 * Rank-selection rule used by the C API SVD truncation policy.
 *
 * Related types:
 * - [`t4a_threshold_scale`] sets whether the threshold is relative or
 *   absolute.
 * - [`t4a_singular_value_measure`] sets whether values or squared values are
 *   measured.
 * - [`t4a_svd_truncation_policy`] combines the rule with the other SVD
 *   truncation knobs.
 *
 * # Examples
 *
 * ```
 * use tensor4all_capi::t4a_truncation_rule;
 * use tensor4all_core::TruncationRule;
 *
 * assert_eq!(
 *     TruncationRule::from(t4a_truncation_rule::PerValue),
 *     TruncationRule::PerValue
 * );
 * assert_eq!(
 *     TruncationRule::from(t4a_truncation_rule::DiscardedTailSum),
 *     TruncationRule::DiscardedTailSum
 * );
 * ```
 */
typedef enum t4a_truncation_rule {
  /**
   * Apply the threshold independently to each singular value.
   */
  T4A_TRUNCATION_RULE_PER_VALUE = 0,
  /**
   * Apply the threshold to the cumulative discarded tail.
   */
  T4A_TRUNCATION_RULE_DISCARDED_TAIL_SUM = 1,
} t4a_truncation_rule;

/**
 * TreeTN contraction method exposed through the C API.
 */
typedef enum t4a_contract_method {
  /**
   * Zip-up contraction with on-the-fly truncation.
   */
  T4A_CONTRACT_METHOD_ZIPUP = 0,
  /**
   * Variational fit-based contraction.
   */
  T4A_CONTRACT_METHOD_FIT = 1,
  /**
   * Naive dense contraction.
   */
  T4A_CONTRACT_METHOD_NAIVE = 2,
} t4a_contract_method;

/**
 * Factorization algorithms exposed through the C API.
 */
typedef enum t4a_factorize_alg {
  /**
   * Singular value decomposition.
   */
  T4A_FACTORIZE_ALG_SVD = 0,
  /**
   * QR decomposition.
   */
  T4A_FACTORIZE_ALG_QR = 1,
  /**
   * Rank-revealing LU decomposition.
   */
  T4A_FACTORIZE_ALG_LU = 2,
  /**
   * Cross interpolation.
   */
  T4A_FACTORIZE_ALG_CI = 3,
} t4a_factorize_alg;

/**
 * Canonical form used for orthogonalization and canonicalization.
 */
typedef enum t4a_canonical_form {
  /**
   * Unitary / QR-based canonicalization.
   */
  T4A_CANONICAL_FORM_UNITARY = 0,
  /**
   * LU-based canonicalization.
   */
  T4A_CANONICAL_FORM_LU = 1,
  /**
   * Cross-interpolation-based canonicalization.
   */
  T4A_CANONICAL_FORM_CI = 2,
} t4a_canonical_form;

/**
 * Status code type for C API
 */
typedef int StatusCode;

/**
 * Opaque index type for the C API.
 */
typedef struct t4a_index {
  const void *_private;
} t4a_index;

/**
 * Opaque canonical QTT layout descriptor.
 */
typedef struct t4a_qtt_layout {
  const void *_private;
} t4a_qtt_layout;

/**
 * Opaque tree tensor network type for the C API.
 */
typedef struct t4a_treetn {
  const void *_private;
} t4a_treetn;

/**
 * Opaque reusable TreeTN evaluator type for the C API.
 */
typedef struct t4a_treetn_evaluator {
  const void *_private;
} t4a_treetn_evaluator;

/**
 * Opaque tensor type for the C API.
 */
typedef struct t4a_tensor {
  const void *_private;
} t4a_tensor;

/**
 * Explicit SVD truncation policy exposed through the C API.
 *
 * This is the ABI-facing mirror of [`tensor4all_core::SvdTruncationPolicy`].
 * Pass it to SVD-based C API entry points to choose the threshold value, the
 * threshold scale, whether singular values are squared first, and whether the
 * truncation rule is per value or tail-sum based.
 *
 * Related types:
 * - [`t4a_threshold_scale`] controls relative vs absolute thresholding.
 * - [`t4a_singular_value_measure`] controls value vs squared-value
 *   measurement.
 * - [`t4a_truncation_rule`] controls per-value vs discarded-tail-sum
 *   truncation.
 *
 * # Examples
 *
 * ```
 * use tensor4all_capi::{
 *     t4a_singular_value_measure, t4a_svd_truncation_policy, t4a_threshold_scale,
 *     t4a_truncation_rule,
 * };
 * use tensor4all_core::{SingularValueMeasure, SvdTruncationPolicy, ThresholdScale, TruncationRule};
 *
 * let ffi_policy = t4a_svd_truncation_policy {
 *     threshold: 1e-8,
 *     scale: t4a_threshold_scale::Absolute,
 *     measure: t4a_singular_value_measure::SquaredValue,
 *     rule: t4a_truncation_rule::DiscardedTailSum,
 * };
 * let core_policy = SvdTruncationPolicy::from(ffi_policy);
 * assert_eq!(core_policy.threshold, 1e-8);
 * assert_eq!(core_policy.scale, ThresholdScale::Absolute);
 * assert_eq!(core_policy.measure, SingularValueMeasure::SquaredValue);
 * assert_eq!(core_policy.rule, TruncationRule::DiscardedTailSum);
 * ```
 */
typedef struct t4a_svd_truncation_policy {
  /**
   * Threshold value used by the selected scale/rule combination.
   */
  double threshold;
  /**
   * Relative or absolute threshold interpretation.
   */
  enum t4a_threshold_scale scale;
  /**
   * Singular-value quantity used for thresholding.
   */
  enum t4a_singular_value_measure measure;
  /**
   * Rank-selection rule.
   */
  enum t4a_truncation_rule rule;
} t4a_svd_truncation_policy;

/**
 * The provided output buffer is too small for the result.
 */
#define T4A_BUFFER_TOO_SMALL -5

/**
 * An internal error occurred (e.g., a panic was caught).
 */
#define T4A_INTERNAL_ERROR -6

/**
 * An invalid argument was provided.
 */
#define T4A_INVALID_ARGUMENT -2

/**
 * The requested API exists but is not implemented yet.
 */
#define T4A_NOT_IMPLEMENTED -7

/**
 * A null pointer was passed where a valid pointer was required.
 */
#define T4A_NULL_POINTER -1

/**
 * Operation completed successfully.
 */
#define T4A_SUCCESS 0

/**
 * Too many tags would be added to a TagSet (exceeds maximum).
 */
#define T4A_TAG_OVERFLOW -3

/**
 * A tag string exceeds the maximum allowed length.
 */
#define T4A_TAG_TOO_LONG -4

/**
 * Clone an index handle.
 */
StatusCode t4a_index_clone(const struct t4a_index *src, struct t4a_index **out);

/**
 * Get the dimension of an index.
 */
StatusCode t4a_index_dim(const struct t4a_index *ptr, size_t *out_dim);

/**
 * Compare two full index handles for equality.
 */
StatusCode t4a_index_equal(const struct t4a_index *lhs,
                           const struct t4a_index *rhs,
                           int32_t *out_equal);

/**
 * Query whether an index has the provided tag.
 */
StatusCode t4a_index_has_tag(const struct t4a_index *ptr, const char *tag, int32_t *out_has_tag);

/**
 * Hash the full index value for process-local hash tables.
 */
StatusCode t4a_index_hash(const struct t4a_index *ptr, uint64_t *out_hash);

/**
 * Check whether an index handle is assigned.
 */
int32_t t4a_index_is_assigned(const struct t4a_index *obj);

/**
 * Get the explicit identity of an index.
 */
StatusCode t4a_index_id(const struct t4a_index *ptr, uint64_t *out_id);

/**
 * Create a new index with explicit tags and prime level.
 */
StatusCode t4a_index_new(size_t dim, const char *tags_csv, int64_t plev, struct t4a_index **out);

/**
 * Create a new index with explicit identity, tags, and prime level.
 */
StatusCode t4a_index_new_with_id(size_t dim,
                                 uint64_t id,
                                 const char *tags_csv,
                                 int64_t plev,
                                 struct t4a_index **out);

/**
 * Return a new index handle with prime level reset to zero.
 */
StatusCode t4a_index_noprime(const struct t4a_index *ptr, struct t4a_index **out);

/**
 * Get the prime level of an index.
 */
StatusCode t4a_index_plev(const struct t4a_index *ptr, int64_t *out_plev);

/**
 * Return a new index handle with prime level incremented by one.
 */
StatusCode t4a_index_prime(const struct t4a_index *ptr, struct t4a_index **out);

/**
 * Release an index handle.
 */
void t4a_index_release(struct t4a_index *obj);

/**
 * Return a new index handle with an explicit prime level.
 */
StatusCode t4a_index_set_plev(const struct t4a_index *ptr, int64_t plev, struct t4a_index **out);

/**
 * Copy tags as a comma-separated UTF-8 string.
 */
StatusCode t4a_index_tags(const struct t4a_index *ptr,
                          uint8_t *buf,
                          size_t buf_len,
                          size_t *out_len);

/**
 * Retrieve the last error message.
 *
 * # Arguments
 * * `buf` - Output buffer for the error message (UTF-8, null-terminated).
 *   Pass null to query required length only.
 * * `buf_len` - Size of the buffer in bytes.
 * * `out_len` - Output: required buffer length including null terminator.
 *
 * # Returns
 * * `T4A_SUCCESS` - Message written (or length query succeeded).
 * * `T4A_NULL_POINTER` - `out_len` is null.
 * * `T4A_BUFFER_TOO_SMALL` - Buffer too small; `out_len` has the required size.
 */
StatusCode t4a_last_error_message(uint8_t *buf, size_t buf_len, size_t *out_len);

/**
 * Materialize the forward affine operator `y = A * x + b` as a chain-shaped
 * TreeTN using the Fused QTT layout.
 *
 * `a_num[i + k * m]` and `a_den[i + k * m]` hold the numerator and
 * denominator of `A[i, k]` (column-major, length `m * n`, where `i`
 * is the row index 0..m and `k` is the column index 0..n). `b_num[i]`
 * and `b_den[i]` describe the `i`-th component of `b` (length `m`).
 * `bc[i]` is the boundary condition applied to output coordinate `i`.
 * The resulting TreeTN has `layout->nsites()` nodes, each with fused
 * input and output site indices of dimensions `2^n` and `2^m`
 * respectively.
 *
 * To obtain the pullback operator `f(y) = g(A * y + b)`, materialize the
 * forward operator with this function and transpose at the binding layer
 * (the pullback is exactly the transpose of the forward operator).
 *
 * # Errors
 *
 * Returns `T4A_INVALID_ARGUMENT` if `m == 0`, `n == 0`, `layout->kind()`
 * is not `Fused`, `b_den[i] == 0`, or `a_den[i + k * m] == 0`.
 */
StatusCode t4a_qtransform_affine_materialize(const struct t4a_qtt_layout *layout,
                                             const int64_t *a_num,
                                             const int64_t *a_den,
                                             const int64_t *b_num,
                                             const int64_t *b_den,
                                             size_t m,
                                             size_t n,
                                             const enum t4a_boundary_condition *bc,
                                             struct t4a_treetn **out);

/**
 * Materialize a cumulative-sum transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_cumsum_materialize(const struct t4a_qtt_layout *layout,
                                             size_t target_var,
                                             struct t4a_treetn **out);

/**
 * Materialize a flip transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_flip_materialize(const struct t4a_qtt_layout *layout,
                                           size_t target_var,
                                           enum t4a_boundary_condition bc,
                                           struct t4a_treetn **out);

/**
 * Materialize a Fourier transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_fourier_materialize(const struct t4a_qtt_layout *layout,
                                              size_t target_var,
                                              int32_t forward,
                                              size_t maxbonddim,
                                              double tolerance,
                                              struct t4a_treetn **out);

/**
 * Materialize a phase-rotation transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_phase_rotation_materialize(const struct t4a_qtt_layout *layout,
                                                     size_t target_var,
                                                     double theta,
                                                     struct t4a_treetn **out);

/**
 * Materialize a shift transform directly as a chain-shaped TreeTN.
 */
StatusCode t4a_qtransform_shift_materialize(const struct t4a_qtt_layout *layout,
                                            size_t target_var,
                                            int64_t offset,
                                            enum t4a_boundary_condition bc,
                                            struct t4a_treetn **out);

/**
 * Clone a QTT layout handle.
 */
StatusCode t4a_qtt_layout_clone(const struct t4a_qtt_layout *src, struct t4a_qtt_layout **out);

/**
 * Check whether a QTT layout handle is assigned.
 */
int32_t t4a_qtt_layout_is_assigned(const struct t4a_qtt_layout *obj);

/**
 * Create an immutable canonical QTT layout descriptor.
 */
StatusCode t4a_qtt_layout_new(enum t4a_qtt_layout_kind kind,
                              size_t nvariables,
                              const size_t *variable_resolutions,
                              struct t4a_qtt_layout **out);

/**
 * Release a QTT layout handle.
 */
void t4a_qtt_layout_release(struct t4a_qtt_layout *obj);

/**
 * Copy logical-axis to payload-axis class mapping.
 */
StatusCode t4a_tensor_axis_classes(const struct t4a_tensor *ptr,
                                   size_t *buf,
                                   size_t buf_len,
                                   size_t *out_len);

/**
 * Clone a tensor handle.
 */
StatusCode t4a_tensor_clone(const struct t4a_tensor *src, struct t4a_tensor **out);

/**
 * Contract two tensors by matching common indices.
 */
StatusCode t4a_tensor_contract(const struct t4a_tensor *a,
                               const struct t4a_tensor *b,
                               struct t4a_tensor **out);

/**
 * Copy dense `Complex64` data as interleaved doubles in column-major order.
 */
StatusCode t4a_tensor_copy_dense_c64(const struct t4a_tensor *ptr,
                                     double *buf_interleaved,
                                     size_t n_complex,
                                     size_t *out_len);

/**
 * Copy dense `f64` data in column-major order.
 */
StatusCode t4a_tensor_copy_dense_f64(const struct t4a_tensor *ptr,
                                     double *buf,
                                     size_t buf_len,
                                     size_t *out_len);

/**
 * Copy compact payload `Complex64` data as interleaved doubles.
 */
StatusCode t4a_tensor_copy_payload_c64(const struct t4a_tensor *ptr,
                                       double *buf_interleaved,
                                       size_t n_complex,
                                       size_t *out_len);

/**
 * Copy compact payload `f64` data in payload column-major order.
 */
StatusCode t4a_tensor_copy_payload_f64(const struct t4a_tensor *ptr,
                                       double *buf,
                                       size_t buf_len,
                                       size_t *out_len);

/**
 * Copy tensor dimensions in index order.
 */
StatusCode t4a_tensor_dims(const struct t4a_tensor *ptr,
                           size_t *buf,
                           size_t buf_len,
                           size_t *out_len);

/**
 * Copy cloned index handles describing the tensor axes.
 */
StatusCode t4a_tensor_indices(const struct t4a_tensor *ptr,
                              struct t4a_index **buf,
                              size_t buf_len,
                              size_t *out_len);

/**
 * Check whether a tensor handle is assigned.
 */
int32_t t4a_tensor_is_assigned(const struct t4a_tensor *obj);

/**
 * Create a dense complex tensor from interleaved column-major data.
 */
StatusCode t4a_tensor_new_dense_c64(size_t rank,
                                    const struct t4a_index *const *index_ptrs,
                                    const double *data_interleaved,
                                    size_t n_complex,
                                    struct t4a_tensor **out);

/**
 * Create a dense real tensor from column-major data.
 */
StatusCode t4a_tensor_new_dense_f64(size_t rank,
                                    const struct t4a_index *const *index_ptrs,
                                    const double *data,
                                    size_t data_len,
                                    struct t4a_tensor **out);

/**
 * Create a complex diagonal tensor from compact diagonal payload data.
 */
StatusCode t4a_tensor_new_diag_c64(size_t rank,
                                   const struct t4a_index *const *index_ptrs,
                                   const double *diag_data_interleaved,
                                   size_t n_complex,
                                   struct t4a_tensor **out);

/**
 * Create a real diagonal tensor from compact diagonal payload data.
 */
StatusCode t4a_tensor_new_diag_f64(size_t rank,
                                   const struct t4a_index *const *index_ptrs,
                                   const double *diag_data,
                                   size_t diag_len,
                                   struct t4a_tensor **out);

/**
 * Create a complex tensor from explicit compact structured storage.
 */
StatusCode t4a_tensor_new_structured_c64(size_t rank,
                                         const struct t4a_index *const *index_ptrs,
                                         const double *data_interleaved,
                                         size_t n_complex,
                                         const size_t *payload_dims,
                                         size_t payload_rank,
                                         const ptrdiff_t *payload_strides,
                                         size_t payload_strides_len,
                                         const size_t *axis_classes,
                                         size_t axis_classes_len,
                                         struct t4a_tensor **out);

/**
 * Create a real tensor from explicit compact structured storage.
 */
StatusCode t4a_tensor_new_structured_f64(size_t rank,
                                         const struct t4a_index *const *index_ptrs,
                                         const double *data,
                                         size_t data_len,
                                         const size_t *payload_dims,
                                         size_t payload_rank,
                                         const ptrdiff_t *payload_strides,
                                         size_t payload_strides_len,
                                         const size_t *axis_classes,
                                         size_t axis_classes_len,
                                         struct t4a_tensor **out);

/**
 * Copy compact payload dimensions.
 */
StatusCode t4a_tensor_payload_dims(const struct t4a_tensor *ptr,
                                   size_t *buf,
                                   size_t buf_len,
                                   size_t *out_len);

/**
 * Get the compact payload length in scalar elements.
 */
StatusCode t4a_tensor_payload_len(const struct t4a_tensor *ptr, size_t *out_len);

/**
 * Get the rank of the compact payload tensor.
 */
StatusCode t4a_tensor_payload_rank(const struct t4a_tensor *ptr, size_t *out_rank);

/**
 * Copy compact payload strides in scalar elements.
 */
StatusCode t4a_tensor_payload_strides(const struct t4a_tensor *ptr,
                                      ptrdiff_t *buf,
                                      size_t buf_len,
                                      size_t *out_len);

/**
 * Compute the QR decomposition of a tensor split by the requested left indices.
 *
 * The tensor is unfolded into a matrix by treating `left_inds[..n_left]` as row
 * indices and all remaining tensor indices as columns, then factorized as
 * `tensor = Q * R`.
 *
 * # Arguments
 * * `tensor` - Input tensor handle to factorize.
 * * `left_inds` - Pointers to the indices that should appear on the left side
 *   of the factorization.
 * * `n_left` - Number of entries in `left_inds`.
 * * `rtol` - Relative truncation tolerance for QR row-norm truncation. Pass
 *   `0.0` to disable truncation and keep the exact QR rank. Pass any other
 *   finite, non-negative value to request truncation for this call.
 * * `out_q` - Output slot that receives a newly allocated `Q` tensor handle on
 *   success.
 * * `out_r` - Output slot that receives a newly allocated `R` tensor handle on
 *   success.
 *
 * # Returns
 * Returns `T4A_SUCCESS` on success and writes owned tensor handles to
 * `out_q` and `out_r`. The caller must release both handles with
 * [`t4a_tensor_release`].
 *
 * # Errors
 * Returns:
 * - `T4A_NULL_POINTER` if `tensor`, any required index pointer, `out_q`, or
 *   `out_r` is null.
 * - `T4A_INVALID_ARGUMENT` if the index split is invalid, QR factorization
 *   fails, or `rtol` is negative or non-finite (for example `NaN` or
 *   `+/-inf`).
 * - `T4A_INTERNAL_ERROR` if the Rust implementation panics while processing
 *   the request.
 */
StatusCode t4a_tensor_qr(const struct t4a_tensor *tensor,
                         const struct t4a_index *const *left_inds,
                         size_t n_left,
                         double rtol,
                         struct t4a_tensor **out_q,
                         struct t4a_tensor **out_r);

/**
 * Get the rank of a tensor.
 */
StatusCode t4a_tensor_rank(const struct t4a_tensor *ptr, size_t *out_rank);

/**
 * Release a tensor handle.
 */
void t4a_tensor_release(struct t4a_tensor *obj);

/**
 * Get the scalar kind of a tensor.
 */
StatusCode t4a_tensor_scalar_kind(const struct t4a_tensor *ptr, enum t4a_scalar_kind *out_kind);

/**
 * Get the storage layout kind of a tensor.
 */
StatusCode t4a_tensor_storage_kind(const struct t4a_tensor *ptr, enum t4a_storage_kind *out_kind);

/**
 * Compute the SVD of a tensor split by the requested left indices.
 */
StatusCode t4a_tensor_svd(const struct t4a_tensor *tensor,
                          const struct t4a_index *const *left_inds,
                          size_t n_left,
                          const struct t4a_svd_truncation_policy *policy,
                          size_t maxdim,
                          struct t4a_tensor **out_u,
                          struct t4a_tensor **out_s,
                          struct t4a_tensor **out_v);

/**
 * Add two tree tensor networks, optionally truncating the result.
 */
StatusCode t4a_treetn_add(const struct t4a_treetn *a,
                          const struct t4a_treetn *b,
                          const struct t4a_svd_truncation_policy *policy,
                          size_t maxdim,
                          struct t4a_treetn **out);

/**
 * Apply a chain-compatible operator TreeTN to a chain state TreeTN.
 *
 * The operator must use dense node names `0..m-1`. `mapped_positions[i]`
 * specifies which state-chain node the operator node `i` acts on. Each mapped
 * operator node must have exactly two site indices, and the corresponding
 * `internal_input_indices[i]` and `internal_output_indices[i]` must point to
 * those indices. Unmapped state nodes are filled with identities by
 * `apply_linear_operator`.
 *
 * For `t4a_contract_method::Fit`, `nfullsweeps == 0` means "use the backend
 * default", which currently resolves to one variational sweep.
 */
StatusCode t4a_treetn_apply_operator_chain(const struct t4a_treetn *operator_,
                                           const struct t4a_treetn *state,
                                           const size_t *mapped_positions,
                                           size_t n_mapped_positions,
                                           const struct t4a_index *const *internal_input_indices,
                                           const struct t4a_index *const *internal_output_indices,
                                           const struct t4a_index *const *true_output_indices,
                                           enum t4a_contract_method method,
                                           const struct t4a_svd_truncation_policy *policy,
                                           size_t maxdim,
                                           size_t nfullsweeps,
                                           double convergence_tol,
                                           struct t4a_treetn **out);

/**
 * Get the canonical region vertices, sorted ascending.
 */
StatusCode t4a_treetn_canonical_region(const struct t4a_treetn *treetn,
                                       size_t *buf,
                                       size_t buf_len,
                                       size_t *out_len);

/**
 * Clone a TreeTN handle.
 */
StatusCode t4a_treetn_clone(const struct t4a_treetn *src, struct t4a_treetn **out);

/**
 * Contract two tree tensor networks with the requested method.
 *
 * For `t4a_contract_method::Fit`, `nfullsweeps == 0` means "use the backend
 * default", which currently resolves to one variational sweep.
 */
StatusCode t4a_treetn_contract(const struct t4a_treetn *a,
                               const struct t4a_treetn *b,
                               enum t4a_contract_method method,
                               const struct t4a_svd_truncation_policy *policy,
                               size_t maxdim,
                               size_t nfullsweeps,
                               double convergence_tol,
                               enum t4a_factorize_alg factorize_alg,
                               double qr_rtol,
                               struct t4a_treetn **out);

/**
 * Evaluate a TreeTN at one or more points using explicit index handles.
 */
StatusCode t4a_treetn_evaluate(const struct t4a_treetn *treetn,
                               const struct t4a_index *const *indices,
                               size_t n_indices,
                               const size_t *values_col_major,
                               size_t n_points,
                               double *out_re,
                               double *out_im);

/**
 * Clone a reusable TreeTN evaluator handle.
 */
StatusCode t4a_treetn_evaluator_clone(const struct t4a_treetn_evaluator *src,
                                      struct t4a_treetn_evaluator **out);

/**
 * Evaluate one or more points using a reusable TreeTN evaluator.
 */
StatusCode t4a_treetn_evaluator_evaluate(const struct t4a_treetn_evaluator *evaluator,
                                         const size_t *values_col_major,
                                         size_t n_points,
                                         double *out_re,
                                         double *out_im);

/**
 * Check whether a reusable TreeTN evaluator handle is assigned.
 */
int32_t t4a_treetn_evaluator_is_assigned(const struct t4a_treetn_evaluator *obj);

/**
 * Create a reusable TreeTN evaluator for explicit index handles.
 */
StatusCode t4a_treetn_evaluator_new(const struct t4a_treetn *treetn,
                                    const struct t4a_index *const *indices,
                                    size_t n_indices,
                                    struct t4a_treetn_evaluator **out);

/**
 * Release a reusable TreeTN evaluator handle.
 */
void t4a_treetn_evaluator_release(struct t4a_treetn_evaluator *obj);

/**
 * Fuse connected current-node groups into the requested target topology.
 */
StatusCode t4a_treetn_fuse_to(const struct t4a_treetn *treetn,
                              const size_t *target_vertices,
                              size_t n_target_vertices,
                              const struct t4a_index *const *target_siteinds,
                              const size_t *target_siteinds_len,
                              const size_t *target_edge_sources,
                              const size_t *target_edge_targets,
                              size_t n_target_edges,
                              struct t4a_treetn **out);

/**
 * Compute the inner product of two tree tensor networks.
 */
StatusCode t4a_treetn_inner(const struct t4a_treetn *a,
                            const struct t4a_treetn *b,
                            double *out_re,
                            double *out_im);

/**
 * Check whether a TreeTN handle is assigned.
 */
int32_t t4a_treetn_is_assigned(const struct t4a_treetn *obj);

/**
 * Get the bond index on the edge between two vertices.
 */
StatusCode t4a_treetn_linkind(const struct t4a_treetn *treetn,
                              size_t v1,
                              size_t v2,
                              struct t4a_index **out);

/**
 * Solve `(a0 + a1 * operator) * x = rhs` for `x` as a TreeTN.
 *
 * The solver returns only the solution TreeTN. The Rust-side `SquareLinsolveResult`
 * also tracks sweep metadata, but that is not yet exposed through the C ABI.
 *
 * `mapped_vertices` and the four index arrays provide optional per-vertex
 * index mappings when the operator uses internal site indices distinct from
 * the `init` / `rhs` site indices. Pass `n_mapped_vertices == 0` to disable
 * mappings.
 *
 * Current limitation: the sweep-based backend still assumes that `init` and
 * `rhs` share the same true site-index set. The mapping arrays bridge the
 * operator's internal indices to those true indices, but they do not yet
 * support solving between distinct `init` and `rhs` true index spaces.
 */
StatusCode t4a_treetn_linsolve(const struct t4a_treetn *operator_,
                               const struct t4a_treetn *rhs,
                               const struct t4a_treetn *init,
                               size_t center_vertex,
                               const size_t *mapped_vertices,
                               size_t n_mapped_vertices,
                               const struct t4a_index *const *true_input_indices,
                               const struct t4a_index *const *internal_input_indices,
                               const struct t4a_index *const *true_output_indices,
                               const struct t4a_index *const *internal_output_indices,
                               const struct t4a_svd_truncation_policy *policy,
                               size_t maxdim,
                               size_t nfullsweeps,
                               double krylov_tol,
                               size_t krylov_maxiter,
                               size_t krylov_dim,
                               double a0,
                               double a1,
                               double convergence_tol,
                               struct t4a_treetn **out);

/**
 * Get the neighbors of a vertex.
 */
StatusCode t4a_treetn_neighbors(const struct t4a_treetn *treetn,
                                size_t vertex,
                                size_t *buf,
                                size_t buf_len,
                                size_t *out_len);

/**
 * Create a tree tensor network from an array of tensors.
 */
StatusCode t4a_treetn_new(const struct t4a_tensor *const *tensors,
                          size_t n_tensors,
                          struct t4a_treetn **out);

/**
 * Compute the norm of the tree tensor network.
 */
StatusCode t4a_treetn_norm(struct t4a_treetn *treetn, double *out_norm);

/**
 * Get the number of vertices in the tree tensor network.
 */
StatusCode t4a_treetn_num_vertices(const struct t4a_treetn *treetn, size_t *out_n);

/**
 * Orthogonalize the tree tensor network to a vertex using the requested form.
 *
 * When `force == 0`, this uses smart canonicalization:
 * - If the network is already canonical at `vertex` with `form`, the call is a no-op.
 * - If the network is already canonicalized with a different form, the call returns
 *   `T4A_INVALID_ARGUMENT`. Pass a nonzero `force` to re-canonicalize with a different form.
 */
StatusCode t4a_treetn_orthogonalize(struct t4a_treetn *treetn,
                                    size_t vertex,
                                    enum t4a_canonical_form form,
                                    int force);

/**
 * Release a TreeTN handle.
 */
void t4a_treetn_release(struct t4a_treetn *obj);

/**
 * Restructure a TreeTN using split, swap, and optional final truncation phases.
 */
StatusCode t4a_treetn_restructure_to(const struct t4a_treetn *treetn,
                                     const size_t *target_vertices,
                                     size_t n_target_vertices,
                                     const struct t4a_index *const *target_siteinds,
                                     const size_t *target_siteinds_len,
                                     const size_t *target_edge_sources,
                                     const size_t *target_edge_targets,
                                     size_t n_target_edges,
                                     const struct t4a_svd_truncation_policy *split_policy,
                                     size_t split_maxdim,
                                     int split_final_sweep,
                                     size_t swap_maxdim,
                                     double swap_rtol,
                                     const struct t4a_svd_truncation_policy *final_policy,
                                     size_t final_maxdim,
                                     struct t4a_treetn **out);

/**
 * Scale a tree tensor network by a complex scalar.
 */
StatusCode t4a_treetn_scale(const struct t4a_treetn *treetn,
                            double re,
                            double im,
                            struct t4a_treetn **out);

/**
 * Replace the tensor at a specific vertex.
 */
StatusCode t4a_treetn_set_tensor(struct t4a_treetn *treetn,
                                 size_t vertex,
                                 const struct t4a_tensor *tensor);

/**
 * Get the site indices attached to a vertex.
 */
StatusCode t4a_treetn_siteinds(const struct t4a_treetn *treetn,
                               size_t vertex,
                               struct t4a_index **buf,
                               size_t buf_len,
                               size_t *out_len);

/**
 * Split current nodes to match the requested target topology.
 */
StatusCode t4a_treetn_split_to(const struct t4a_treetn *treetn,
                               const size_t *target_vertices,
                               size_t n_target_vertices,
                               const struct t4a_index *const *target_siteinds,
                               const size_t *target_siteinds_len,
                               const size_t *target_edge_sources,
                               const size_t *target_edge_targets,
                               size_t n_target_edges,
                               const struct t4a_svd_truncation_policy *policy,
                               size_t maxdim,
                               int final_sweep,
                               struct t4a_treetn **out);

/**
 * Reassign site indices to target vertices using scheduled swap transport.
 */
StatusCode t4a_treetn_swap_site_indices(const struct t4a_treetn *treetn,
                                        const struct t4a_index *const *assignment_siteinds,
                                        const size_t *assignment_target_vertices,
                                        size_t n_assignments,
                                        size_t maxdim,
                                        double rtol,
                                        struct t4a_treetn **out);

/**
 * Get the tensor at a specific vertex.
 */
StatusCode t4a_treetn_tensor(const struct t4a_treetn *treetn,
                             size_t vertex,
                             struct t4a_tensor **out);

/**
 * Contract all bonds and materialize the TreeTN as a dense tensor.
 */
StatusCode t4a_treetn_to_dense(const struct t4a_treetn *treetn, struct t4a_tensor **out);

/**
 * Truncate the tree tensor network bond dimensions using SVD-based truncation.
 */
StatusCode t4a_treetn_truncate(struct t4a_treetn *treetn,
                               const struct t4a_svd_truncation_policy *policy,
                               size_t maxdim);

#endif  /* TENSOR4ALL_CAPI_H */
